### ISSUE TITLE
1.20dev gatekeeper does not send request packets to grantor

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#694] opened 2024-07-07 12:08 UTC
1.2dev NIC XL710, gatekeeper stops sending request packets to grantor after running for a while, causing flow to fail to obtain policies. All packets are rejected
<img width="1412" alt="image" src="https://github.com/AltraMayor/gatekeeper/assets/104405912/7f62d8c1-d2dc-4977-be9b-b90cd951f250">
There is no error log output, and no memory segmentation faults.

**Comment by ShawnLeung87** [comment] 2024-07-07 12:15
The first time it happened was at 22:30 on July 6, 2024, Beijing time. I had to completely stop Gatekeeper and then start Gatekeeper to temporarily solve the problem of not sending request packets. If I use the restart command, Gatekeeper still cannot solve the problem of not sending request packets.
The second time it happened was at 17:30 on July 7, 2024, Beijing time.

**Comment by ShawnLeung87** [comment] 2024-07-07 12:34
The second time, an attack occurred, and the total tot_pkts_size of the 4 cores reached 92g
<img width="1407" alt="image" src="https://github.com/AltraMayor/gatekeeper/assets/104405912/6423bd20-1f52-4569-a7e1-301fe1558da7">

**Comment by ShawnLeung87** [comment] 2024-07-08 02:07
Error Log:
GK/5 2024-07-07 17:27:17 ERR mb_alloc_entry(): failed to get a new mailbox entry (errno=105): No buffer space available
GK/5 2024-07-07 17:27:17 ERR submit_ggu: allocation of mailbox message failed
GK/5 2024-07-07 17:27:17 WARNING acl: IPv4 ACL function 2 failed on back iface
GK/5 2024-07-07 17:27:17 ERR mb_alloc_entry(): failed to get a new mailbox entry (errno=105): No buffer space available
GK/5 2024-07-07 17:27:17 ERR submit_ggu: allocation of mailbox message failed
GK/5 2024-07-07 17:27:17 WARNING acl: IPv4 ACL function 2 failed on back iface
GK/6 2024-07-07 17:27:17 ERR mb_alloc_entry(): failed to get a new mailbox entry (errno=105): No buffer space available
GK/6 2024-07-07 17:27:17 ERR submit_ggu: allocation of mailbox message failed
GK/6 2024-07-07 17:27:17 WARNING acl: IPv4 ACL function 2 failed on back iface
GK/5 2024-07-07 17:27:17 ERR mb_alloc_entry(): failed to get a new mailbox entry (errno=105): No buffer space available
GK/5 2024-07-07 17:27:17 ERR submit_ggu: allocation of mailbox message failed
GK/5 2024-07-07 17:27:17 WARNING acl: IPv4 ACL function 2 failed on back iface
GK/5 2024-07-07 17:27:17 ERR mb_alloc_entry(): failed to get a new mailbox entry (errno=105): No buffer space available
GK/6 2024-07-07 17:27:17 ERR mb_alloc_entry(): failed to get a new mailbox entry (errno=105): No buffer space available
GK/6 2024-07-07 17:27:17 ERR submit_ggu: allocation of mailbox message failed
GK/6 2024-07-07 17:27:17 WARNING acl: IPv4 ACL function 2 failed on back iface
GK/6 2024-07-07 17:27:17 ERR mb_alloc_entry(): failed to get a new mailbox entry (errno=105): No buffer space available
GK/6 2024-07-07 17:27:17 ERR submit_ggu: allocation of mailbox message failed
GK/6 2024-07-07 17:27:17 WARNING acl: IPv4 ACL function 2 failed on back iface
GK/6 2024-07-07 17:27:17 ERR mb_alloc_entry(): failed to get a new mailbox entry (errno=105): No buffer space available

**Comment by ShawnLeung87** [comment] 2024-07-08 02:16
GK/6 2024-07-07 01:07:26 ERR Failed to enqueue a bulk of 1 requests - only 0 requests are enqueued
GK/4 2024-07-07 01:07:26 ERR Failed to enqueue a bulk of 2 requests - only 0 requests are enqueue


LLS/0 2024-07-07 07:26:44 ERR Received "Fragmentation required, and DF flag set" ICMP packet on the back interface from source IP 10.11.10.193; check MTU along path
LLS/0 2024-07-07 09:03:06 ERR Received "Fragmentation required, and DF flag set" ICMP packet on the back interface from source IP 10.11.10.193; check MTU along path
LLS/0 2024-07-07 17:10:24 ERR Received "Fragmentation required, and DF flag set" ICMP packet on the back interface from source IP 10.11.10.193; check MTU along path

**Comment by AltraMayor** [comment] 2024-07-08 09:50
Hi @ShawnLeung87,

What's the parameter `destination_bw_gbps` value in file `lua/ggu.lua`?

**Comment by AltraMayor** [comment] 2024-07-08 10:04
> GK/5 2024-07-07 17:27:17 ERR mb_alloc_entry(): failed to get a new mailbox entry (errno=105): No buffer space available
> GK/5 2024-07-07 17:27:17 ERR submit_ggu: allocation of mailbox message failed
> GK/5 2024-07-07 17:27:17 WARNING acl: IPv4 ACL function 2 failed on back iface

This is likely not the root cause of the problem but a sign that you should add 1 to the parameter `mailbox_max_entries_exp` in the file `lua/ggu.lua`. For example, the default value is 7, so change it to 8.

**Comment by ShawnLeung87** [comment] 2024-07-08 10:13
ggu parameter
<img width="844" alt="image" src="https://github.com/AltraMayor/gatekeeper/assets/104405912/c7df9fc7-f46b-42cb-b207-c4582ef8704f">
sol parameter
<img width="1046" alt="image" src="https://github.com/AltraMayor/gatekeeper/assets/104405912/0a7a3aa5-9458-4991-9ab7-d6f36f0a23ac">

**Comment by AltraMayor** [comment] 2024-07-08 10:14
> LLS/0 2024-07-07 07:26:44 ERR Received "Fragmentation required, and DF flag set" ICMP packet on the back interface from source IP 10.11.10.193; check MTU along path

Is `10.11.10.193` a Grantor server?

**Comment by ShawnLeung87** [comment] 2024-07-08 10:16
10.11.10.193 is the route gateway

**Comment by AltraMayor** [comment] 2024-07-08 10:17
Your parameter `destination_bw_gbps` in file `lua/ggu.lua` is fine. Just update the parameter `mailbox_max_entries_exp` in the file `lua/ggu.lua` to 8.

**Comment by ShawnLeung87** [comment] 2024-07-08 10:31
The MTU is not changed. The MTU from the backend to the route gateway is set to 2048.

**Comment by AltraMayor** [comment] 2024-07-08 10:38
> The MTU is not changed. The MTU from the backend to the route gateway is set to 2048.

You must check **all** the interfaces on the paths between the Gatekeeper and Grantor servers, not only the gateway interface connected to the Gatekeeper server's back interface. The log entry `LLS/0 2024-07-07 07:26:44 ERR Received "Fragmentation required, and DF flag set" ICMP packet on the back interface from source IP 10.11.10.193; check MTU along path` is informing you that the packets sent to the Grantor servers are being dropped **somewhere** in the network due to their size.

**Comment by ShawnLeung87** [comment] 2024-07-09 02:06
> > MTU 不变，后端到路由网关的 MTU 设置为 2048。
> 
> 您必须检查Gatekeeper 和 Grantor 服务器之间路径上的**所有**`LLS/0 2024-07-07 07:26:44 ERR Received "Fragmentation required, and DF flag set" ICMP packet on the back interface from source IP 10.11.10.193; check MTU along path`接口，而不仅仅是连接到 Gatekeeper 服务器后接口的网关接口。日志条目通知您，发送到 Grantor 服务器的大型数据包由于其大小而被丢弃在网络中的**某个地方。**
> 
> 例如，您的网关可能从接口 A 上的 Gatekeeper 服务器获取数据包，并通过接口 B 传输这些数据包。您说接口 A 的 MTU 为 2048，但如果接口 B 没有，数据包就会被丢弃。此外，您可能会发现路径上的其他接口也需要更改其 MTU。

I found this problem. It is because the Juniper MX router lacp mtu is set to 2048, which will subtract more than the value of other devices. The value should be set to 2094. The gatepeer and grantor mtu remain unchanged.

**Comment by AltraMayor** [comment] 2024-07-09 14:24
Great. If the problem is solved now, you can close this issue.

**Closed** 2024-07-15 06:27 UTC
