### ISSUE TITLE
GK incorrectly calculates RSS hash in software

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#265] opened 2019-05-21 15:34 UTC
The GK block uses the RSS hash when doing flow lookups.

First, it uses it when receiving a packet on the front interface to do a flow lookup. For this one, it uses the RSS hash calculated by hardware:

https://github.com/AltraMayor/gatekeeper/blob/master/gk/main.c#L1389-L1390

Second, when Grantor sends Gatekeeper a decision regarding a flow (IP src, dst pari), the GK block calculates the RSS hash in software to then (lookup and) add that decision to the flow table:

https://github.com/AltraMayor/gatekeeper/blob/master/gk/main.c#L840-L841

It seems that the software hash does not match the hardware hash. I have an example where Gatekeeper receives a packet on the front interface, whose flow key (EtherType + IP pair) and RSS hash are:

```
flow key: 00 08 00 00 ac 1f 02 ab ac 20 04 c8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
hash val: 3017585628
```

And when receiving a policy decision for this packet, its flow key and hash value is:

```
flow key: 00 08 00 00 ac 1f 02 ab ac 20 04 c8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
hash val: 1787437985
```

The entry added to the hash table therefore will not be found when packets from this flow come into the front interface.

**Comment by cjdoucette** [comment] 2019-05-21 16:21
Actually, the description above may or may not be a bug. I removed the RSS hash from the hash table lookup and insert (and so it only used the flow keys), and there's still a bug where the flow entry found when the packet arrives at Gatekeeper is not matching the flow entry found when a decision regarding that flow arrives from Grantor.

**Comment by cjdoucette** [comment] 2019-05-21 17:03
I can confirm that incorrect computation of the RSS hash seems to be the issue.

Another way this bug manifests itself: when receiving a policy decision from Grantor, the GGU selects a GK instance using `get_responsible_gk_mailbox()`. If this hash is wrong, it could choose a different GK block than the one that received the original request.

In other words, we can have the following sequence of events:

1. A packet is hashed in hardware to GK instance 1 on the front interface.
2. GK instance 1 creates a request entry in the flow table.
2. A request packet is sent to Grantor.
3. Grantor decides to grant the packet, and sends the policy decision back to Gatekeeper.
4. The GGU block receives the decision and computes the RSS hash of the flow in software. Based on this hash, GK instance 2 is selected.
5. GK instance 2 adds a granted flow entry to its flow table.
6. More packets from this flow come in and are hashed by hardware to GK instance 1, but GK instance 1 only has the request flow entry. Requests continue to flow and come back to GK instance 2.

It seems that we should more closely look at `rss_ip_flow_hf()` and its callers, as well as our usage of the software-computed RSS hash with the hash table insertions and lookups.

**Comment by mengxiang0811** [comment] 2019-05-21 21:55
From the definition of the flow key (https://github.com/AltraMayor/gatekeeper/blob/master/include/gatekeeper_flow.h#L26-L41), we know that the size of the flow key should be ``2+16+16=34`` bytes, however, in your example output, the flow key has ``36`` bytes. Could you please verify where are the two bytes from?

**Comment by AltraMayor** [comment] 2019-05-21 21:57
The two bytes may be due to memory alignment to make the flow key 32-bit aligned.

**Comment by cjdoucette** [comment] 2019-05-21 22:06
Yes, I believe there are padded zero bytes.

Is this comment relevant? https://github.com/AltraMayor/gatekeeper/blob/master/lib/flow.c#L31-L32

**Comment by AltraMayor** [comment] 2019-05-21 22:10
We are already using `rte_convert_rss_key()` in `gatekeeper_init_network()`. So, unless there's a bug there, that comment doesn't help here.

**Comment by AltraMayor** [comment] 2019-05-21 22:12
If the padded bytes are not being zeroed before the calculation of the RSS hash, it could be what is causing this bug.

**Comment by mengxiang0811** [comment] 2019-05-21 22:13
Indeed, we are using the special converted key. As far as I remembered, when I tried to use the recommended RSS Verification Suite from [82599 datasheet page 309-310](https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/82599-10-gbe-controller-datasheet.pdf) , it works as expected for both IPv4 and IPv6. After that we use the randomized RSS key.

**Comment by AltraMayor** [comment] 2019-05-21 22:15
I don't think anyone has tested the hashes after we added the randomized key.

**Comment by cjdoucette** [comment] 2019-05-21 22:16
In case it's relevant, this behavior was found on Amazon using the ENA.

**Comment by mengxiang0811** [comment] 2019-05-21 22:18
Should we have a test with the fixed RSS key from the 82599 datasheet to verify whether it works under the recommended RSS Verification Suite on Amazon using the ENA?

**Comment by cjdoucette** [comment] 2019-05-21 22:21
Sure -- if there's a patch you can write that I can apply, I can do it in the testbed.

If it's simple, feel free to just write what the lines to be changed are here and I'll make the changes. If it's more complicated, you could write a git patch and push it to a branch, then I could do `git cherry-pick` to apply it and test it.

**Comment by AltraMayor** [comment] 2019-05-21 22:23
Another thing that can be done is to test the randomized key on our server XIA1. If it works there, it's an ENA bug. If it's an ENA bug, we can report the bug on [DPDK Bugzilla](https://bugs.dpdk.org/).

**Comment by mengxiang0811** [comment] 2019-05-21 22:35
Here is a simple hack for RSS test: https://github.com/mengxiang0811/gatekeeper/tree/rss-test

**Comment by cjdoucette** [comment] 2019-05-21 23:42
That did not seem to fix the problem on ENA.

I added the following lines to the GK block after it receives a packet on its front interface:

```
uint32_t rss_hash_val = rss_ip_flow_hf(&packet.flow, 0, 0);     
printf("hardware: %u, software: %u\n", pkt->hash.rss, rss_hash_val);
```

In other words, just to print out the hardware and software hashes. On the xia1 server, these hashes match, but on the Amazon testbed, they do not match.

Is the issue that the ixgbe NICs like 82599 and Amazon NICs like ENA use different hash functions, and our software hash is modeled after the ixgbe hash?

**Comment by AltraMayor** [comment] 2019-05-22 00:57
ENA's hash key seem to be hardcore: https://github.com/amzn/amzn-drivers/issues/24

So the solution is to find out this key from the source and use it when ENA is the driver.

**Comment by mengxiang0811** [comment] 2019-05-22 05:23
By diving into the ENA's source code, the function [ena_com_hash_key_allocate()](https://github.com/amzn/amzn-drivers/blob/f559c2eb3043f2bb7ebcfc709f3d5bd8d4b53e10/kernel/fbsd/ena/ena_com/ena_com.c#L983) allocating ENA hash key will call [ENA_MEM_ALLOC_COHERENT()](https://github.com/amzn/amzn-drivers/blob/f559c2eb3043f2bb7ebcfc709f3d5bd8d4b53e10/kernel/fbsd/ena/ena_com/ena_plat.h#L304) or [dma_zalloc_coherent()](https://github.com/amzn/amzn-drivers/blob/aa8ab36becf007e34a547dac63114f304ee5e0ca/kernel/linux/common/ena_com/ena_com.c#L1045), which seems filling up the RSS hash key by using DMA, thus, the key may depend on the content in that memory region.

**Comment by AltraMayor** [comment] 2019-05-22 11:38
If we can test that a driver cannot set the RSS key, we can issue a warning in the log, and load the key from the driver. If this works, it may be a solution general enough to help with other drivers beside ENA.

**Comment by AltraMayor** [comment] 2019-05-23 12:23
Checking out [the matrix of features available in networking drivers that DPDK supports](http://doc.dpdk.org/guides/nics/overview.html#id1), I've found that the majority of the drivers support "RSS key update" and "RSS reta update", but a number of them do not. So working with the key of the NIC when it cannot be updated is the way to go.

**Comment by mengxiang0811** [comment] 2019-05-23 18:18
As RSS configuration is on [per port](https://doc.dpdk.org/api/rte__ethdev_8h.html#a6000dca62f9815414b3f3b9c5d8be62f) granularity, and Gatekeeper is supposed to support multiple ports, therefore the issue is that different ports may have different RSS hash keys in ENA.

**Comment by AltraMayor** [comment] 2019-05-23 18:46
It is fine to abort the initialization if two ports that are supposed to work together cannot have the same RSS key. The message should suggest getting other NICs if possible or running with a single NIC.

**Comment by mengxiang0811** [comment] 2019-05-23 22:41
I have hack for updating RSS hash key properly at pull request #274 . Please have a try whether this works.

**Comment by cjdoucette** [comment] 2019-05-24 16:09
Since the ENA driver does not support `rte_eth_dev_rss_hash_conf_get()`, that call returns an error, and consequently and the setup aborts because `check_port_offloads()` returns an error.

**Comment by AltraMayor** [comment] 2019-05-24 16:44
Let's have a patch that checks that the NICs can update the RSS key and abort initialization if they don't; the log message should cite this issue as a reference. Once this patch is merged, we can move this issue to the milestone "Advanced features" to think of it later on since the first two deployments are not going to rely on Amazon.

**Comment by cjdoucette** [comment] 2019-05-24 16:49
I can get around this issue for now by testing with only one GK instance and not using the RSS hash as part of the lookup.

**Comment by mengxiang0811** [comment] 2019-05-24 17:17
If the single GK instance works, then we can simply set ``iface->rss = false`` when the above scenario occurs instead of returning.

**Comment by cjdoucette** [comment] 2019-05-24 17:21
The only issue with that is that I think we need to use `rte_hash_lookup()` and `rte_hash_add()` instead of `rte_hash_lookup_with_hash()` and `rte_hash_add_with_hash()` in this case.

That's possibly a bug that happens regardless of ability to update the RSS key.

**Comment by mengxiang0811** [comment] 2019-05-24 18:27
Agreed. As long as Gatekeeper doesn't use RSS, we may have to use ``rte_hash_lookup()`` and ``rte_hash_add_key()`` instead of ``rte_hash_lookup_with_hash()`` and ``rte_hash_add_key_with_hash()``.

**Comment by mengxiang0811** [comment] 2019-05-28 19:39
To operate on the IP flow hash table, the hash value is always needed: even using ``rte_hash_lookup()`` and ``rte_hash_add_key()``, the hash table will call ``rss_ip_flow_hf()`` to calculate the hash value for an IP flow.

To keep the interfaces simpler, we may still use ``rte_hash_lookup_with_hash()`` and ``rte_hash_add_key_with_hash()`` even when RSS is not supported. The hash value for the IP flow can be obtained by explicitly calling``rss_ip_flow_hf()``.

**Closed** 2019-05-31 20:17 UTC
Labels: bug
