### ISSUE TITLE
i40e_flow_set_fdir_inset(): Invalid input set

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#661] opened 2023-10-13 04:09 UTC
[2023-10-13 01:12:16] Main/0: ggu: calculate_mempool_config_para: total_pkt_burst = 32 packets, total_rx_desc = 640 descriptors, total_tx_desc = 256 descriptors, max_num_pkt = 928 packets, num_mbuf = 1023 packets.
[2023-10-13 01:12:16] Main/0: cps: calculate_mempool_config_para: total_pkt_burst = 4256 packets, total_rx_desc = 640 descriptors, total_tx_desc = 256 descriptors, max_num_pkt = 5152 packets, num_mbuf = 8191 packets.
[2023-10-13 01:12:20] Main/0: ethertype_flow_add(front): EtherType=0x806 flow supported
[2023-10-13 01:12:20] Main/0: ethertype_flow_add(back): EtherType=0x806 flow supported
[2023-10-13 01:12:20] Main/0: Back interface link speed: 5000000000 bytes per second
[2023-10-13 01:12:20] Main/0: Cycles per byte (19.155254) represented as a rational: 36644 / 1913
i40e_flow_set_fdir_inset(): Invalid input set
[2023-10-13 01:12:20] Main/0: ipv4_flow_add(back, DstIP=10.11.10.195 UDP SrcPort=41120/0xffff DstPort=45232/0xffff): cannot validate IPv4 flow, errno=22 (Invalid argument), rte_flow_error_type=13: Invalid ETH item
[2023-10-13 01:12:20] Main/0: Cannot register IPv4 flow on the back interface; falling back to software filters
i40e_flow_set_fdir_inset(): Invalid input set
[2023-10-13 01:12:20] Main/0: ipv4_flow_add(front, DstIP=10.12.11.2 TCP SrcPort=0/0x0 DstPort=0/0x0): cannot validate IPv4 flow, errno=22 (Invalid argument), rte_flow_error_type=13: Invalid ETH item
[2023-10-13 01:12:20] Main/0: Cannot register IPv4 flow on the front interface; falling back to software filters
i40e_flow_set_fdir_inset(): Invalid input set

The current version branch of gatekeeper is master
i40e flow dir classification exception log appears during restart

**Comment by AltraMayor** [comment] 2024-05-29 14:35
Duplicate of #685.

**Closed by AltraMayor** 2024-05-29 14:35 UTC
