### ISSUE TITLE
Testing Gatekeeper before first test in production

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#197] opened 2019-02-22 14:59 UTC
The ultimate test of Gatekeeper will be in production, but before someone feels comfortable deploying Gatekeeper in their infrastructure, we must test our code well to avoid obvious bugs of ever hitting production.

We have been generously granted access to the [Chameleon](https://www.chameleoncloud.org/) testbed, which meets and exceeds all our needs at this stage of our tests.

As important as testing is to document how to perform the tests. This will help other collaborators to reproduce and adapt the tests to their own purposes as well as provide newcomers with examples of how to set Gatekeeper up. Thus, the tests must be documented on our wiki. This testing documentation will be an excellent starting point later on when we have the resources to automate testing.

Given the number of tests, this issue needs all hands it can get. So jump into any test with which you can help.

What to test:
* Request channel.
  + If no policy decision is made (e.g. no Grantor server is deployed), Gatekeeper should forward at most 5% of the incoming bandwidth. This test should check how precise the 5% allocation of the bandwidth is as well as see if Gatekeeper won't crash or misbehave under SYN floods.
  + Verify that the priorities associated to request packets are exactly as designed. This test can build on the previous test to make sure that a client following the expected behavior, that is, backing off when a capability is not granted right away, can overcome clients flooding the network.

* Granted channel.
  + Check that the allocated bandwidth to a given flow is respect and the precision of it is good. One must also test that expiring capabilities are renewed.
  + Check that rejected flows are rejected and that these policies decisions expire as designed.
  + Check parameters of the policies; especially the granted policy that will receive packets warning that the decision is about to expire (capability renewal). The goal here is to test all parameters that policy decisions have.

* Stress tests.
  + Test eviction of flow entries while Gatekeeper's flow table is overloaded. We must make sure that nothing bad happens during this attack condition.
  + Test the behavior of Gatekeeper and Grantor servers while a DDoS attack. We must source DDoS tools here to simulate the attack.

* Operational tests.
  + Check that Gatekeeper and Grantor servers reply to pings and that they reply at at most the configured ICMP rated.
  + GT blocks reload policy via the dynamic configuration block.
  + Dump internal tables (e.g. ARP/ND, flow table, LPM table) via the dynamic configuration block.
  + Flushing flow tables.
  + Check that bonded interfaces work properly and that LACP works. LACP must deal with loss of ports.
  + Check that a routing daemon works with Gatekeeper. The very minimum is for the daemon to receive routes from the vantage point and export this information a router in the back network.
  + Gratuitous ARP/ND packets are used in production to quickly move traffic from a decommissioned host to another. We must check that the LLS block is properly handling these gratuitous packets.

**Comment by AltraMayor** [comment] 2019-02-28 11:16
Another test is to verify that Gatekeeper can process 64-byte packets at at least 10Gbps. If this is not the case, issue #36, or part of it, must be addressed to reach this performance level. This performance rate will likely be raised in future releases, but it's enough for the first deployment.

**Comment by AltraMayor** [comment] 2019-03-27 18:00
One more test: checking that maximum MTU packets (typically 1500) can enter a Gatekeeper server and arrive at its final destination.

**Comment by cjdoucette** [comment] 2019-04-05 18:42
Along with the request channel tests, we should test the case where the back interface's bandwidth is higher than the bandwidth afforded by the path to the Grantor server overall. The Solicitor block sends requests at a rate of 5% of the back interface capacity, but this is only an approximation of 5% of the capacity of the channel.

If there are drops, is the request channel still effectively getting 5%? In other words, are the drops uniform across requests and granted packets? I don't know if that is necessarily the case, since we have one entity bursting 5% of the link bandwidth and multiple entities (GK instances) using whatever is left.

**Comment by mengxiang0811** [comment] 2019-04-14 21:19
To improve the efficiency, repeatability and reproducibility of Gatekeeper test, we need to have a complex appliance on Chameleon as explained in issue #244

**Comment by AltraMayor** [comment] 2019-04-18 17:58
Testing merging traffic coming from two or more Gatekeeper servers at a router between the Gatekeeper servers and Grantor servers.

**Comment by AltraMayor** [comment] 2019-06-06 19:45
Testing Gatekeeper and Grantor servers receiving fragmented packets. While Gatekeeper servers shouldn't have any issue with fragmented packets, unless there is a bug somewhere, Grantor servers have to be tested with the following cases:
1. Normal fragmentation, that is, fragmented packets are assembled, have their policy decision replied, and are forwarded to their destinations;
2. Receiving fragmented packets that are never completed;
3. Receiving fragmented packets that, once assembled, are larger the MTU of the interface of the Grantor servers.

**Comment by cjdoucette** [comment] 2020-03-19 20:32
I just applied the following tests to the current master branch:

- Running an iperf client through Gatekeeper to test for IPv4 UDP and TCP traffic
- Running an iperf client through Gatekeeper to test for IPv6 UDP and TCP traffic
- Running an echo client from the back network through Gatekeeper to the front network.

And Gatekeeper passed all tests.

This is on top of the functional and operational tests that were performed over the past few months that were mentioned through this thread. I will continue to form our testing apparatus and try to cover as many tests as possible, but for now I am satisfied with the level of testing for Gatekeeper's correctness and am closing this issue.

**Closed by cjdoucette** 2020-03-19 20:32 UTC
Labels: Operational demand, help wanted
